### ISSUE TITLE
Feature request: Already fulfilled dependencies

### ISSUE THREAD

**Issue by cphaarmeyer** [ashbaldry/depcheck#3]
For instance when using `ggplot2` as dependency, we get `scales` for free (see https://www.tidyverse.org/blog/2019/05/itdepends/ 3.). It would be helpful to detect these situations automatically (and not display the warning).

**Comment by ashbaldry** [comment]
That's a good idea. Let me make sure I am on the same page: 

If in my project I am creating a load of `ggplot`s, and for one of them `scales::percent` is used, then `{scales}` wouldn't be flagged because of the extensive use of `{ggplot2}` and it is a free dependency. However, in the event `{ggplot2}` is flagged for low use then `{scales}` would also be flagged. Probably wouldn't happen for the example above, but can see it occurring with other packages.

**Comment by ashbaldry** [comment]
@cphaarmeyer the main branch should now work as expected. Let me know whether it works or not :)

**Comment by cphaarmeyer** [comment]
Works for me, great package btw :)
